# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0005_auto_20160630_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='breed',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
