# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-04-24 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0006_listing_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
    ]
